# Generated by Django 4.0 on 2021-12-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField()),
                ('event_address', models.TextField()),
                ('event_pc', models.TextField()),
                ('event_dt', models.DateTimeField()),
                ('event_details', models.TextField()),
            ],
        ),
    ]
