# Generated by Django 4.0 on 2021-12-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
