# Generated by Django 4.0 on 2021-12-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_event_lat_event_event_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_host',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
