# Generated by Django 4.0 on 2021-12-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_img',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
