# Generated by Django 4.0 on 2021-12-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_event_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_f_name', models.TextField()),
                ('user_l_name', models.TextField()),
                ('user_descrip', models.TextField()),
                ('F_link', models.TextField()),
                ('T_link', models.TextField()),
                ('I_link', models.TextField()),
                ('S_link', models.TextField()),
            ],
        ),
    ]
